Updated dotfiles for Xubuntu 18.04: install snap packages

diff --git a/playbooks/launch b/playbooks/launch
--- a/playbooks/launch
+++ b/playbooks/launch
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 
-#git pull
+if [[ $EUID -eq 0 ]]; then
+   echo "This script cannot be run as root" 
+   exit 1
+fi
 
 if [[ `uname` == 'Linux' ]]; then
   ansible-playbook -i inventory ubuntu.yml
